---
title: "homework-03"
format: 
  html:
    toc: true # use this to display a table of contents
execute:
  message: false # use this to make sure messages don't show up
  warning: false # use this to make sure warnings don't show up
author: "Sumaiya Alvi"
date: "2026-02-26"
---

[Link to Github repository](https://github.com/sumaiyaalvi/ENVS-193DS_homework-03.git)

[Deployed html url](https://sumaiyaalvi.github.io/ENVS-193DS_homework-03/code/homework-03.html)

# Set up tasks

```{r}
#| label: load packages and data
library(tidyverse) #general use
library(here) #file organization
library(janitor) #cleaning data frames
library(readxl) #reading excel files


salinity <- read_csv(
  here( #allows you to write in file paths
    "data", #folder
    "salinity-pickleweed.csv" #salinity data
  ))

screentime <- read_csv(
  here( 
    "data", #data folder
    "screentime.csv" #personal data 
  ))
```
# Problem 1: Slough soil salinity

## a. An appropriate test

The appropriate tests to determine the strength of the relationship between California pickleweed biomass and soil salinity are Pearson’s r correlation and simple linear regression, since both biomass (measured in grams) and soil salinity (measured as electrical conductivity in mS/cm) are continuous variables. Pearson’s r measures the strength and direction of the linear association between salinity and biomass, and quantifies how closely changes in salinity are related to changes in plant biomass. In contrast, simple linear regression treats biomass as the response variable and salinity as the predictor, estimating how much biomass changes for each one-unit increase in salinity, and using $R^2$ to quantify how much of the variation in biomass is explained by salinity.

## b. 

